plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  ExtraDetails: true

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - table
    - key

Lint/AmbiguousBlockAssociation:
  AllowedPatterns:
    - change

Metrics/AbcSize:
  AllowedMethods:
    - render

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

# Allow underscore to indicate private variable.
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Naming/MethodParameterName:
  AllowedNames:
    - 'x'
    - 'y'
    - 'r'

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

RSpec/ExampleLength:
  Exclude:
    - 'spec/github_repo_fetcher/api_response_service_spec.rb'
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Exclude: []

RSpec/VerifiedDoubles:
  Exclude: []

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/FormatStringToken:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SymbolArray:
  MinSize: 3

Style/WordArray:
  MinSize: 3
