name: Debug Repository Dispatch Events

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'
      - 'vercel.deployment.created'
      - 'vercel.deployment.ready'
      - 'vercel.deployment.error'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Payload
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.action }}"
          echo "Full event payload:"
          echo '${{ toJSON(github.event) }}' | jq .

      - name: Check Environment
        run: |
          echo "Environment: ${{ github.event.client_payload.environment || 'NOT_SET' }}"
          echo "URL: ${{ github.event.client_payload.url || 'NOT_SET' }}"
          echo "Git SHA: ${{ github.event.client_payload.git.sha || 'NOT_SET' }}"
